---
- name: Ensure sysctl settings are configured (Session)
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: 'dev.tty.ldisc_autoload', value: '0' }
    - { key: 'fs.protected_fifos', value: '2' }
    - { key: 'fs.protected_hardlinks', value: '1' }
    - { key: 'fs.protected_regular', value: '2' }
    - { key: 'fs.protected_symlinks', value: '1' }
    - { key: 'fs.suid_dumpable', value: '0' }
    - { key: 'kernel.core_uses_pid', value: '1' }
    - { key: 'kernel.ctrl-alt-del', value: '0' }
    - { key: 'kernel.dmesg_restrict', value: '1' }
    - { key: 'kernel.kptr_restrict', value: '2' }
    - { key: 'kernel.modules_disabled', value: '1' }
    - { key: 'kernel.perf_event_paranoid', value: '3' }
    - { key: 'kernel.randomize_va_space', value: '2' }
    - { key: 'kernel.sysrq', value: '0' }
    - { key: 'kernel.unprivileged_bpf_disabled', value: '1' }
    - { key: 'net.core.bpf_jit_harden', value: '2' }
    - { key: 'net.ipv4.conf.all.accept_redirects', value: '0' }
    - { key: 'net.ipv4.conf.all.accept_source_route', value: '0' }
    - { key: 'net.ipv4.conf.all.bootp_relay', value: '0' }
    - { key: 'net.ipv4.conf.all.forwarding', value: '0' }
    - { key: 'net.ipv4.conf.all.log_martians', value: '1' }
    - { key: 'net.ipv4.conf.all.mc_forwarding', value: '0' }
    - { key: 'net.ipv4.conf.all.proxy_arp', value: '0' }
    - { key: 'net.ipv4.conf.all.rp_filter', value: '1' }
    - { key: 'net.ipv4.conf.all.send_redirects', value: '0' }
    - { key: 'net.ipv4.conf.default.accept_redirects', value: '0' }
    - { key: 'net.ipv4.conf.default.accept_source_route', value: '0' }
    - { key: 'net.ipv4.conf.default.log_martians', value: '1' }
    - { key: 'net.ipv6.conf.all.accept_redirects', value: '0' }
    - { key: 'net.ipv6.conf.default.accept_redirects', value: '0' }
    - { key: 'net.ipv6.conf.all.accept_source_route', value: '0' }
    - { key: 'net.ipv6.conf.default.accept_source_route', value: '0' }

- name: Ensure sysctl settings are persistent
  copy:
    dest: /etc/sysctl.d/99-zzz_custom.conf
    content: |
      dev.tty.ldisc_autoload = 0
      fs.protected_fifos = 2
      fs.protected_hardlinks = 1
      fs.protected_regular = 2
      fs.protected_symlinks = 1
      fs.suid_dumpable = 0
      kernel.core_uses_pid = 1
      kernel.ctrl-alt-del = 0
      kernel.dmesg_restrict = 1
      kernel.kptr_restrict = 2
      kernel.modules_disabled = 1
      kernel.perf_event_paranoid = 3
      kernel.randomize_va_space = 2
      kernel.sysrq = 0
      kernel.unprivileged_bpf_disabled = 1
      net.core.bpf_jit_harden = 2
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.all.accept_source_route = 0
      net.ipv4.conf.all.bootp_relay = 0
      net.ipv4.conf.all.forwarding = 0
      net.ipv4.conf.all.log_martians = 1
      net.ipv4.conf.all.mc_forwarding = 0
      net.ipv4.conf.all.proxy_arp = 0
      net.ipv4.conf.all.rp_filter = 1
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.accept_redirects = 0
      net.ipv4.conf.default.accept_source_route = 0
      net.ipv4.conf.default.log_martians = 1
      net.ipv6.conf.all.accept_redirects = 0
      net.ipv6.conf.default.accept_redirects = 0
      net.ipv6.conf.all.accept_source_route = 0
      net.ipv6.conf.default.accept_source_route = 0
