---
- name: Secure SSH configuration
  copy:
    dest: /etc/ssh/sshd_config.d/99-custom
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      PermitEmptyPasswords no

      ChallengeResponseAuthentication no
      KerberosAuthentication no
      GSSAPIAuthentication no

      X11Forwarding no
      PermitUserEnvironment no

      AllowAgentForwarding no
      AllowTcpForwarding no
      PermitTunnel no

      MaxAuthTries 3
      LoginGraceTime 20
      
      ClientAliveInterval 300
      MaxSessions 10
  register: ssh_config
      
- name: Restart SSH service
  systemd:
    name: ssh
    state: restarted
  when: ssh_config.changed
    
