---
- name: GitOps
  hosts: all
  become: yes

  vars:
    # Git repo settings
    git_repo_url: https://github.com/sverzegnassi/smarthomelab-server.git
    git_repo_branch: main
    local_dest: "/home/{{ ansible_user }}/.gitops"

    # Users
    podman_user: podrunner
    caddy_user: ubuntu

  pre_tasks:
    - name: Install required packages
      apt:
        name:
          - git
          - ansible
        state: present
        update_cache: yes

  roles:
    - git_diff
    # - files_sync
    # - ansible_playbooks
    - systemd_services
    # - systemd_timers
    - podman_quadlets
    - caddy_config

# TODO: Save log somewhere